# fly.toml app configuration file generated for hermelindo on 2026-03-19T08:28:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hermelindo'
primary_region = 'iad'

[[mounts]]
  source = 'hermes_data'
  destination = '/root/.hermes'
  initial_size = '5gb'

[http_service]
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-4x'
  memory = '2048mb'
